org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
forge_version=52.1.0
forge_version_range=[52,)
loader_version_range=[52,)
mapping_channel=official
mapping_version=1.21.1

## Mod Properties
mod_id=apexballistics
mod_name=Apex Ballistics
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.apexballistics
mod_authors=Apex Ballistics
mod_description=Strategic missiles (ICBM, SLBM, ALCM, SAM), anti-air batteries, and high-tech armor and weapons for Minecraft 1.21.1 Forge.
